version: "3.8"
services:
  pokemon-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokemon-app
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:h2:mem:pokemon_db
      - SPRING_DATASOURCE_USERNAME=sa
      - SPRING_DATASOURCE_PASSWORD=password
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - h2-db

  h2-db:
    image: oscarfonts/h2
    container_name: h2-db
    ports:
      - "9090:8082"
    environment:
      H2_OPTIONS: "-ifNotExists -tcp -webAllowOthers"
